### ISSUE TITLE
TypeError during generation

### ISSUE THREAD

**Issue by cptroot** [ondras/rollup-plugin-graph#1]
I keep getting the following error during generation:

```
[!] TypeError: Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at Object.onwrite (/Users/evand/aspen/ctl/node_modules/rollup-plugin-graph/index.js:39:33)
    at plugin (/usr/local/lib/node_modules/rollup/dist/rollup.js:10561:40)
    at next (/usr/local/lib/node_modules/rollup/dist/rollup.js:154:27)
    at promise.then (/usr/local/lib/node_modules/rollup/dist/rollup.js:158:33)
    at <anonymous>
```

Any suggestions? This is my rollup config file:

```
import graph from "rollup-plugin-graph";

module.exports = {
  external: [
    'jquery',
    'moment',
  ],
  globals: {
    jquery: "$",
    moment: "moment",
  },
  input: "./src/main.js",
  output: {
    file: "./build/graph.dot",
    format: "es",
    name: "ctl",
  },
  plugins: [
    graph({
      prune: true,
    }),
  ],
};
```

**Comment by ondras** [comment]
@cptroot please, what Rollup version are you using?

**Comment by ondras** [comment]
Update: this was broken between rollup 0.47 (works) and rollup 0.48 (fails).

**Comment by ondras** [comment]
Submitted a rollup issue: https://github.com/rollup/rollup/issues/1689

**Comment by cptroot** [comment]
Thanks for figuring that out! I was testing with the newest rollup, 0.50.0.

**Comment by ondras** [comment]
I am aware of a workaround, but would like to know the purpose of this breaking change first.

**Comment by ondras** [comment]
@cptroot please try updating to rollup-plugin-graph@1.2.0, I believe I fixed the issue.

**Comment by cptroot** [comment]
Looks good to me
